baseURL = "https://kodecahya.netlify.com/"
languageCode = "en-us"
title = "KodeCahya.com | Gusti Cahya"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Site Menus
[menu]
    # Navbar Menus
    # [[menu.nav]]
    #     name    = "About"
    #     url     = "about"
    #     weight  = 2
    # [[menu.nav]]
    #     name    = "Service"
    #     url     = "service"
    #     weight  = 3
    [[menu.nav]]
        name    = "Gallery"
        url     = "gallery"
        weight  = 4
    [[menu.nav]]
        name    = "Blog"
        url     = "blog"
        weight  = 5
    # [[menu.nav]]
    #     name    = "Contact"
    #     url     = "contact"
    #     weight  = 6

# Site Params
[params]
    home = "Home"
    logo = "images/logo.png"
    dateFormat = "15 September 2019"
    # Meta data
    description = "Kodecahya is personal website of Gusti Cahya"
    author = "Gusti Cahya"
    # Google Analitycs
    googleAnalitycsID = "Your ID"

    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "images/slider.jpg"
        heading = "Hello, My name is GUSTI CAHYA and i am"
        description = "We don't have to be perfect to start, we just need to start then become perfect, So never stop learning..."
        btn     = false
        btnText = "Subscribe"
        btnURL  = "https://www.youtube.com/channel/UCcq5Z3eGUNprtWgL7D5ZI0A"
        [[params.banner.flipText]]
            title   = "Full-Stack Developer"
        [[params.banner.flipText]]
            title   = "Hybrid Mobile Developer"
        [[params.banner.flipText]]
            title   = "Desktop App Developer"
        [[params.banner.flipText]]
            title   = "Content Creator"

    # Homepage About Section
    [params.about]
        enable  = true
        title   = "ABOUT ME"
        content = "Hello, I am a student who continues to explore knowledge about various aspects related to computers and web technology. <br> <br> I used to use React to create web apps and on this website I use Hugo static site generator."
        image   = "images/about/about.jpg"

    # Call to Action
    [params.cta]
        enable  = true
        title   = "stay connected with me!"
        content = "I'm content creator, <br> I'm trying to share the knowledge I've learned. So keep watching my channel okay! 😎"
        btnText1 = "Channel Youtube"
        btnURL1  = "https://www.youtube.com/channel/UCcq5Z3eGUNprtWgL7D5ZI0A"
        btnText2 = "Instagram"
        btnURL2  = "https://www.instagram.com/gusticahya__/"
        btnText3 = "Blog"
        btnURL3  = "/blog"

    # Portfolio Section On Homepage
    [params.portfolio]
        enable  = false
        title   = "Latest Works"
        subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

    [params.footer]
        [[params.footer.socialIcon]]
            icon = "ion-social-facebook"
            url = "https://www.facebook.com/GustiCahyaX"

        [[params.footer.socialIcon]]
            icon = "ion-social-instagram"
            url = "https://www.instagram.com/gusticahya__/"

        [[params.footer.socialIcon]]
            icon = "ion-social-linkedin"
            url = "https://www.linkedin.com/in/gusti-cahya-68590517b/"
        
        [[params.footer.socialIcon]]
            icon = "ion-social-youtube"
            url = "https://www.youtube.com/channel/UCcq5Z3eGUNprtWgL7D5ZI0A"
