baseURL = "gusticahya.com"
languageCode = "en-us"
title = "GustiCahya.com | Gusti Cahya"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Site Menus
[menu]
    # Navbar Menus
    # [[menu.nav]]
    #     name    = "About"
    #     url     = "about"
    #     weight  = 2
    # [[menu.nav]]
    #     name    = "Service"
    #     url     = "service"
    #     weight  = 3
    [[menu.nav]]
        name    = "Gallery"
        url     = "gallery"
        weight  = 4
    [[menu.nav]]
        name    = "Blog"
        url     = "blog"
        weight  = 5
    # [[menu.nav]]
    #     name    = "Contact"
    #     url     = "contact"
    #     weight  = 6

# Site Params
[params]
    home = "Home"
    logo = "images/logo.png"
    dateFormat = "15 September 2019"
    # Meta data
    description = "gusticahya.com is personal website for Gusti Cahya"
    author = "Gusti Cahya"
    # Google Analitycs
    googleAnalitycsID = "Your ID"

    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "images/slider.jpg"
        heading = "Hello, My name is GUSTI CAHYA and i am"
        description = "We don't need to be perfect to start, we just need to start then become perfect, So never stop learning..."
        btn     = false
        btnText = "Subscribe"
        btnURL  = "https://www.youtube.com/channel/UCcq5Z3eGUNprtWgL7D5ZI0A"
        [[params.banner.flipText]]
            title   = "Full-Stack Developer"
        [[params.banner.flipText]]
            title   = "Hybrid Mobile App Developer"
        [[params.banner.flipText]]
            title   = "Content Creator"

    # Homepage About Section
    [params.about]
        enable  = true
        title   = "ABOUT ME"
        content = "Hello, I'm an experienced full stack developer dedicated to the continuous pursuit of knowledge in various fields of computer science and web technologies. <br><br> With in-depth knowledge of software system design, installation, testing, and maintenance, I have a detail-oriented approach to managing multiple projects simultaneously. So far in my journey, I've used React to build dynamic web applications and used Hugo on this platform. <br><br> My expertise extends to user interface design, comprehensive testing, and effective debugging processes. I excel in both independent projects, demonstrating effective self-management, and in collaborative team environments, contributing to the success of productive teams. <br><br> Pursuit of excellence and keen observation of details ensure the delivery of high-quality software solutions."
        image   = "images/about/about.jpg"

    # Call to Action
    [params.cta]
        enable  = true
        title   = "stay connected with me!"
        content = "I'm content creator, <br> I'm trying to share knowledge from what I've learned. So keep watching my channel okay! 😎"
        btnText1 = "Channel Youtube"
        btnURL1  = "https://www.youtube.com/channel/UCtsWYrn86rR5rTIGLbuMW4Q"
    #   btnText2 = "Instagram"
    #   btnURL2  = "https://www.instagram.com/gusticahya__/"
        btnText3 = "Blog"
        btnURL3  = "/blog"

    # Portfolio Section On Homepage
    [params.portfolio]
        enable  = false
        title   = "Latest Works"
        subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

    [params.footer]
        #[[params.footer.socialIcon]]
        #    icon = "ion-social-facebook"
        #    url = "https://www.facebook.com/GustiCahyaX"

        #[[params.footer.socialIcon]]
        #    icon = "ion-social-instagram"
        #    url = "https://www.instagram.com/gusticahya__/"

        [[params.footer.socialIcon]]
            icon = "ion-social-linkedin"
            url = "https://www.linkedin.com/in/gusti-cahya-68590517b/"
        
        [[params.footer.socialIcon]]
            icon = "ion-social-youtube"
            url = "https://www.youtube.com/channel/UCtsWYrn86rR5rTIGLbuMW4Q"
